version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
    container_name: laravel
    working_dir: /var/www
    expose:
      - 9000
      
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:12.20-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_DB: parkways
      POSTGRES_USER: anonymous
      POSTGRES_PASSWORD: PWOff2022
    ports:
      - "5432:5432"
    
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine-slim
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8005:80"
    depends_on:
      - backend
    networks:
      - app-network
    
